on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: 1.${{ github.run_number }}.0
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Create version
        id: version
        run: |
          git config --global user.name "ygonzalez1"
          git config --global user.email "ygonzalez.work@gmail.com"
          echo "tag: ${{git tag --column --sort -tag | awk '{print $1}' | awk '{split($0,a,"."); print a[1]"."a[2]"."a[3]+1}'}}"
#          echo "::set-output name=new_tag::${{git tag --column --sort -tag | awk '{print $1}' | awk '{split($0,a,"."); print a[1]"."a[2]"."a[3]+1}'}}"

      - name: Create Git Tag
        id: tag
        run: |
          echo "${{ steps.version.outputs.new_tag }}"
          

