on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: portal-comercios
          IMAGE_TAG: 1.${{ secrets.GITHUB_RUN_NUMBER }}.0
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Set Version
        id: version
        run: |
          echo "::set-output name=value::$( pwsh ../version-tool.ps1 next-dev-version )"

      - name: Create a tag
        id: tag
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ github.ref }} merged and created ${{ steps.version.outputs.value }}
          tag: ${{ steps.version.outputs.value }}

      - name: Show Ref
        run: |
          echo "Created version ${{ steps.tag.outputs.ref }}"
          echo "secrets.GITHUB_RUN_NUMBER ${{ secrets.GITHUB_RUN_NUMBER }}"

